package com.company;

import org.graphwalker.core.machine.ExecutionContext;
import org.graphwalker.java.annotation.GraphWalker;

/**
 * Implements the GraphWalker model: src/main/resources/SmallTest.json
 * <p/>
 * The interface SmallTest, that SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn compile
 */
@GraphWalker(value = "random(edge_coverage(100))", start = "v_ENHETPlanner")
public class IKEATest extends ExecutionContext implements IKEAKitchenConfigurator {

  @Override
public void v_PreDefinedENHET() {
    System.out.println("Running: v_PreDefinedENHET");
}

@Override
public void e_clickOpen() {
    System.out.println("Running: e_clickOpen");
}

@Override
public void v_ENHETPlanner() {
    System.out.println("Running: v_ENHETPlanner");
}

@Override
public void e_clickShowIncludedParts() {
    System.out.println("Running: e_clickShowIncludedParts");
}

@Override
public void v_StartFromScratch() {
    System.out.println("Running: v_StartFromScratch");
}

@Override
public void e_clickOnItem() {
    System.out.println("Running: e_clickOnItem");
}

@Override
public void e_clickOnAProductType() {
    System.out.println("Running: e_clickOnAProductType");
}

@Override
public void e_clickViewDesingInPlanner() {
    System.out.println("Running: e_clickViewDesingInPlanner");
}

@Override
public void v_PlannerPageAddProductsMenu() {
    System.out.println("Running: v_PlannerPageAddProductsMenu");
}

@Override
public void v_Menu() {
    System.out.println("Running: v_Menu");
}

@Override
public void e_clickPreDefinedENHET() {
    System.out.println("Running: e_clickPreDefinedENHET");
}

@Override
public void e_clickFinalise() {
    System.out.println("Running: e_clickFinalise");
}

@Override
public void e_clickRemoveDesing() {
    System.out.println("Running: e_clickRemoveDesing");
}

@Override
public void v_DesignSummary() {
    System.out.println("Running: v_DesignSummary");
}

@Override
public void v_ShoppingCart() {
    System.out.println("Running: v_ShoppingCart");
}

@Override
public void e_clickBack() {
    System.out.println("Running: e_clickBack");
}

@Override
public void v_ItemInShoppingBag() {
    System.out.println("Running: v_ItemInShoppingBag");
}

@Override
public void e_clickAddProduct() {
    System.out.println("Running: e_clickAddProduct");
}

@Override
public void e_clickStartFromScratch() {
    System.out.println("Running: e_clickStartFromScratch");
}

@Override
public void e_clickEditDesign() {
    System.out.println("Running: e_clickEditDesign");
}

@Override
public void e_clickExitPlanner() {
    System.out.println("Running: e_clickExitPlanner");
}

@Override
public void e_writeCodeAndClickOpen() {
    System.out.println("Running: e_writeCodeAndClickOpen");
}

@Override
public void v_ProductTypeList() {
    System.out.println("Running: v_ProductTypeList");
}

@Override
public void e_clickOnDifferentStyle() {
    System.out.println("Running: e_clickOnDifferentStyle");
}

@Override
public void e_clickX() {
    System.out.println("Running: e_clickX");
}

@Override
public void v_OpenADesing() {
    System.out.println("Running: v_OpenADesing");
}

@Override
public void e_clickStyleKitchen() {
    System.out.println("Running: e_clickStyleKitchen");
}

@Override
public void v_PlannerPageStyleKitchenMenu() {
    System.out.println("Running: v_PlannerPageStyleKitchenMenu");
}

@Override
public void e_clickGoToShoppingBag() {
    System.out.println("Running: e_clickGoToShoppingBag");
}

@Override
public void e_clickMenu() {
    System.out.println("Running: e_clickMenu");
}


